# Generated by Django 6.0.2 on 2026-02-27 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/artwork/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('medium', models.CharField(blank=True, help_text='e.g. Oil on canvas', max_length=100)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallerycategory')),
            ],
            options={
                'verbose_name': 'Artwork Image',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TattooImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/tattoo/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('style', models.CharField(blank=True, help_text='e.g. Blackwork, Realism', max_length=100)),
                ('body_placement', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallerycategory')),
            ],
            options={
                'verbose_name': 'Tattoo Image',
                'ordering': ['sort_order'],
            },
        ),
    ]
