# Generated by Django 6.0.2 on 2026-02-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/featured/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Featured Work',
                'verbose_name_plural': 'Featured Works',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, upload_to='home/')),
                ('hero_title', models.CharField(default='Art of the Harbor', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_cta_text', models.CharField(default='View My Work', max_length=50, verbose_name='CTA button text')),
                ('hero_cta_link', models.URLField(blank=True, help_text='URL for the CTA button')),
                ('intro', models.TextField(blank=True)),
                ('philosophy_statement', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
    ]
