# Generated by Django 6.0.2 on 2026-02-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait_image', models.ImageField(blank=True, upload_to='about/')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('bio_heading', models.CharField(blank=True, max_length=255)),
                ('bio_text', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
